name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Formatting (Prettier)
        run: npx prettier --check . || echo "Run 'npx prettier --write .' to fix formatting issues." && exit 1

      - name: Fix Code Formatting (Prettier)
        if: failure() 
        run: npx prettier --write .
